todo
ss14Starlight/space-station-14 pull request #155
Opened 2024-12-14 16:06 UTC by fqqf

Stardew emotes system
![image](https://github.com/user-attachments/assets/82a77d68-7784-4379-b408-5f83c563ef8b)
![image](https://github.com/user-attachments/assets/f0c56261-f929-4075-bf19-400e029218f4)
![image](https://github.com/user-attachments/assets/5f5d769f-a4ca-4190-841e-eb0ea9aaa4dd)

**Changelog**

2024-12-14 16:10 UTC, fqqf commented
will be implemented via Spawn() effect over entity. Yeah, thats it.

2024-12-14 21:03 UTC, fqqf commented
![emote_start](https://github.com/user-attachments/assets/1e1934f5-c6ae-49a3-9940-c7eaf22e5c09)
![emote_nervous](https://github.com/user-attachments/assets/d641fd97-7b88-4dca-bd62-eacfeb741ef6)
![emote_lenny](https://github.com/user-attachments/assets/84f36e92-585b-4f80-99e1-d5ef454dbb25)
![emote_mark](https://github.com/user-attachments/assets/643bdd0f-13a2-4d17-a0fa-4306b366fc93)

2024-12-14 21:41 UTC, fqqf commented
![image](https://github.com/user-attachments/assets/6866a93a-e744-4d79-9832-123d8254886c)

2024-12-15 06:36 UTC, fqqf commented
https://github.com/user-attachments/assets/a9ea240d-8c20-4db1-bc8b-a0d8c6a005db

2024-12-15 11:27 UTC, Rinary1 requested changes

2024-12-15 11:27 UTC, Rinary1 commented on Resources/Prototypes/_StarLight/Entities/Effects/cloud_emotes.yml
parents? Like, basic emotion with default things, like TImedDespawn, + you need:
```
- type: Transform
  noRot: true
  ```

2024-12-15 18:59 UTC, fqqf commented
ready to review

2024-12-15 19:05 UTC, fqqf commented
not my linter, its from cluwne

2024-12-15 19:29 UTC, Rinary1 approved these changes

2024-12-15 19:49 UTC, fqqf commented
oops, forgot changelog. Fixed

2024-12-16 09:43 UTC, CrimeMoot commented
it's so cute

2024-12-16 10:36 UTC, merged