Adds Hotel Station
ss14Starlight/space-station-14 pull request #173
Opened 2024-12-18 20:41 UTC by PubliclyExecutedPig

## Short description

Adds Hotel Station, a midpop/highpop station made for starlight. heavily wip rn
## Why we need to add this

## Media (Video/Screenshots)

![image](https://github.com/user-attachments/assets/70f396cd-5e4e-4978-b4a2-54b5f041b564)

## Checks

- [X] I do not require assistance to complete the PR.
- [ ] Before posting/requesting review of a PR, I have verified that the changes work.
- [X] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [X] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**
 - add: Added Hotel Station

2024-12-18 20:41 UTC, PubliclyExecutedPig commented
still wip, will post updates here

2024-12-27 12:55 UTC, PubliclyExecutedPig commented
map renderer isnt working :blunt: 
![image](https://github.com/user-attachments/assets/cab784a5-0c7d-461d-87ee-f371a7a02fff)

2024-12-28 09:41 UTC, Rinary1 commented
@ss14-Starlight

2024-12-28 15:28 UTC, PubliclyExecutedPig commented
i forgot to add signs but now im done, except for fixing this error lol

2024-12-28 17:04 UTC, PubliclyExecutedPig commented
drafting for a sec bc i wanna add decals and stuff

2024-12-28 17:55 UTC, JustAdler commented
> drafting for a sec bc i wanna add decals and stuff

maybe also decal arrows for hop line? same from cargo

2024-12-28 19:27 UTC, PubliclyExecutedPig commented
> > drafting for a sec bc i wanna add decals and stuff
> 
> maybe also decal arrows for hop line? same from cargo

done, just the map thing isnt working bc of some bug to do with missing red bruise pack textures or something

2024-12-29 09:33 UTC, Rinary1 commented
merge master

2024-12-29 10:36 UTC, PubliclyExecutedPig commented
> merge master(Starlight)

done

2024-12-29 12:11 UTC, Rinary1 requested changes

2024-12-29 12:11 UTC, Rinary1 commented on Resources/Prototypes/_StarLight/Maps/hotel.yml
Law department? Or it didn't mapped?
+ Add it to map pool(/Pools/Default.yml)

2024-12-29 13:21 UTC, PubliclyExecutedPig commented on Resources/Prototypes/_StarLight/Maps/hotel.yml
There's a magistrate office and a courtroom, also a small Internal affairs agent office

2024-12-29 13:22 UTC, PubliclyExecutedPig commented on Resources/Prototypes/_StarLight/Maps/hotel.yml
I'll add it when I'm home

2024-12-29 20:31 UTC, Rinary1 requested changes

2024-12-29 20:31 UTC, Rinary1 commented on Resources/Prototypes/_StarLight/Maps/hotel.yml
> +  mapName: 'StarlightHotel'
????

2024-12-29 20:34 UTC, merged