Added Brigmedical Defib
ss14Starlight/space-station-14 pull request #197
Opened 2024-12-29 15:01 UTC by KillerTheFlareon

## Short description

Add a handheld defib to the brigmedic loadout, as in, spawns with the brigmedic.
## Why we need to add this

A lot of the time a brigmedic may need to revive a near-death or dead security officer during an emergency and carrying around an entire full-sized defibrillator can be quite cumbersome. This was also in the original brigmedic PR, as one of the goals to implement but due to time constraints .miracula has not been able to do it, and offered for me to do it instead. Which I accepted.
## Media (Video/Screenshots)

https://github.com/user-attachments/assets/cd2acbe4-0a7b-47f1-8f4d-dbb365b58ae8

## Checks

- [x] I do not require assistance to complete the PR.
- [x] Before posting/requesting review of a PR, I have verified that the changes work.
- [x] I have added screenshots/videos of the changes, or this PR does not change in-game mechanics.
- [x] I affirm that my changes are licensed under the [Starlight Fork License](https://github.com/ss14Starlight/space-station-14/blob/Starlight/LICENSE-Starlight.TXT) and grant permission for use in this repository under its conditions.

**Changelog**

:cl: Killer Tamashi
- add: Added Brigmedic Defibrillator

2024-12-31 22:02 UTC, PubliclyExecutedPig commented
meow *beats you with defib*

2024-12-31 23:58 UTC, KillerTheFlareon commented
Lmao

2025-01-02 03:59 UTC, KillerTheFlareon commented
Okay! I couldn't pull a miracle out of me and create entirely new code that's a Frankenstein of the "x many hits left" and "% of charge left" system, but it was rather simple to make a new battery that only works with the brigmedical defib.

A whitelist was used to ensure that no other battery fits in the brigmedical defib other than the brigmedical defib battery, and has roughly about 2 uses.

2025-01-03 14:23 UTC, Rinary1 requested changes

2025-01-03 14:23 UTC, Rinary1 commented on Resources/Prototypes/_StarLight/Entities/Objects/Specific/Medical/defib.yml
> +          startingItem: PowerCellTiny
why this here?

2025-01-03 14:27 UTC, KillerTheFlareon commented on Resources/Prototypes/_StarLight/Entities/Objects/Specific/Medical/defib.yml
> +          startingItem: PowerCellTiny
I figured I'd put everything in one place since this file is probably only going to be used for the brigmedic defib anyhow

2025-01-03 14:34 UTC, Rinary1 commented on Resources/Prototypes/_StarLight/Entities/Objects/Specific/Medical/defib.yml
> +          startingItem: PowerCellTiny
> I figured I'd put everything in one place since this file is probably only going to be used for the brigmedic defib anyhow

lol, no, it's general file only for defibs.

2025-01-03 14:35 UTC, KillerTheFlareon commented on Resources/Prototypes/_StarLight/Entities/Objects/Specific/Medical/defib.yml
> +          startingItem: PowerCellTiny
Alright, give me a couple of minutes to fix this then

2025-01-03 14:52 UTC, KillerTheFlareon commented on Resources/Prototypes/_StarLight/Entities/Objects/Specific/Medical/defib.yml
> +          startingItem: PowerCellTiny
fixed.

2025-01-03 15:07 UTC, merged